print("Hello, this is my first Pycharm code")
print("Again!!!!")
print("Hello, this is my first Pycharm code")
print("Again!!!!")
print("Hello, this is my first Pycharm code")
print("Again!!!!")
print("Hello, this is my first Pycharm code")
print("Again!!!!")
print("Hello, this is my first Pycharm code")
print("Again!!!!")